### ISSUE TITLE
Test conditions in code

### ISSUE THREAD

**Issue by c4s4** [jinzhu/configor#1]
I would **not** put test conditions in production code, such as:

```go
if isTest, _ := regexp.MatchString("/_test/", os.Args[0]); isTest {
    return "test"
}
```

**Comment by jinzhu** [comment]
this is not for testing purpose, but as a feature.

`ENV` will return `test` if you are running `go test`, then will load your test configuration.

`os.Args[0]` looks like `/tmp/go-build440363972/github.com/jinzhu/configor/_test/configor.test` when run `go test`
