### ISSUE TITLE
configor.Load(&config, "./config.yml") will not return an error if the config file is not found

### ISSUE THREAD

**Issue by tikiatua** [jinzhu/configor#20]
Hi there,

Thank you for this nice library. We did just notice some unexpected behavior:

The load method will print an error message "Failed to find configuration ./config.yml" but will not return an error. This will cause the program to assume that a configuration was correctly loaded on continue on if no specific additional checks are implemented.

I think it would be better if the load method would return an error if no config file was found.

**Comment by phproot** [comment]
测试了一下，无法加载相对路径，但是绝对路径则可以正常加载。

**Comment by phproot** [comment]
可以暂时使用：
```
var appPath, _ = os.Getwd()
configor.Load(&Config, appPath+"/configs/config.yml")
```

**Comment by blaskovicz** [comment]
@jinzhu why was this closed? I found this silent failure a little confusing as well.

**Comment by blaskovicz** [comment]
Ah, nvm, I realized the workaround was to provide a full path to have it error out!

**Comment by onkarbanerjee** [comment]
> Ah, nvm, I realized the workaround was to provide a full path to have it error out!

@blaskovicz what's the workaround here? sorry but i did not get it
