### ISSUE TITLE
Refactor moved yaml.v2 library back to yaml.v1

### ISSUE THREAD

**Issue by beornf** [jinzhu/configor#25]
Since the tests still refer to `gopkg.in/yaml.v2` was this change intended: https://github.com/jinzhu/configor/commit/0af3f7b50bf927700a30508aafb71ab6aee2089b#diff-7d1c2a3334601b6c1958aae0a594cba8R14

**Comment by cryptix** [comment]
I'd also like a clearification.

**Comment by jinzhu** [comment]
Sorry for that, it is a mistake ;(

**Comment by beornf** [comment]
Thanks @jinzhu!
