### ISSUE TITLE
No indication when there are unmatched keys in config file

### ISSUE THREAD

**Issue by reuben453** [jinzhu/configor#27]
Hello,

When loading a config file into a struct, like this: `configor.Load(&Config, "config.yml")`, there is no indication if there are any keys in config.yml that do not match any field in the Config struct. The Load function will silently load whatever it can and return.

It would be nice to have the ability to return an error when there are keys in the file that do not match any field in the struct. That will make it easier to catch errors in the config file.

**Comment by reuben453** [comment]
#26 fixes this for yaml and toml files.

@jinzhu, should I keep this open till I can add support for json files also?

**Comment by jinzhu** [comment]
Hello @reuben453 

If it is possible to add json support, you can keep it open, otherwise, you could close it.

Thank you for your PR.
