### ISSUE TITLE
Document how to use []string with ENV variables

### ISSUE THREAD

**Issue by stevenroose** [jinzhu/configor#29]
When the config struct contains a slice, f.e. of strings, the config files allow for using lists and command line arguments allow for repeating arguments.

How does that work for environment variables?

**Comment by prochac** [comment]
```
var Config struct {
	StringArray []string `default:"['foo','bar']" env:"STRING_ARRAY"`

	StructArray []struct {
		Name string `default:"poop"`
	} `default:"[{'name':'foo'},{}]" env:"STRUCT_ARRAY"`
}

func main() {
	configor.Load(&Config)

	for i, item := range Config.StringArray {
		fmt.Printf("%d %+v\n", i, item)
	}

	for i, item := range Config.StructArray {
		fmt.Printf("%d %+v\n", i, item)
	}
}
```
`$ env STRING_ARRAY=["foo","baz"] go run .`
```
0 foo
1 baz
0 {Name:foo}
1 {Name:poop}
```

**Comment by stevenroose** [comment]
Soon after that question last year, I developed [gonfig](https://github.com/stevenroose/gonfig) which does environment variables, command line flags and config files (JSON, YAML and TOML) all at once. I've been using it in all my Go projects since.

But thanks for answering the question! :)

**Comment by jinzhu** [comment]
https://github.com/jinzhu/configor/pull/41
