### ISSUE TITLE
Support command line flags

### ISSUE THREAD

**Issue by stevenroose** [jinzhu/configor#30]
If configor could support command line flags as well, this package would beat others like viper. Most configuration packages require calling a ton of special functions and have separate handling of different config ways. 

If configor could support CLI flags while sticking to the simple struct-approach, that would be awesome!

**Comment by alex-oleshkevich** [comment]
you can achieve that like:
```go
// main.go
func init() {
	configor.Load(&config.Config, "config.yml")
	pflag.StringVar(&config.Config.RabbitDSN, "amqp", config.Config.RabbitDSN, "RabbitMQ DSN")
}

func main() {
   log.Println(config.Config.RabbitDSN)
}
```

**Comment by stevenroose** [comment]
In the meantime, I created [gonfig](https://github.com/stevenroose/gonfig), which does both config files, flags and environment variables.
