### ISSUE TITLE
not working search env "if CONFIGOR_ENV not set, environment will be development by default"

### ISSUE THREAD

**Issue by mymtw** [jinzhu/configor#32]
I have 2 files:
1. `config.yml`
2. `config.development.yml`

`configor.Load(&cfg, "config/environments/config.yml")`
`go run main.go`
not loading my file automatically: `config.development.yml`
instead he loading `config.yml`

_**But in earlier version(January 2017) it loaded config.development.yml**_

**Comment by jinzhu** [comment]
Just checked, should works now.

Thank you for your report.
