### ISSUE TITLE
Nested YAML issue

### ISSUE THREAD

**Issue by PlkMarudny** [jinzhu/configor#35]
Hi,

How to define a type for the following YAML?

    part1:
    - level1:
     - level2:
       -level3:
           key1: value1
           key2: value2

Is the scenario supported in general?

**Comment by delphinus** [comment]
How about this?

```go
type setting struct {
  Part1 []struct {
    Level1 []struct {
      Level2 []struct {
        Level3 struct {
          Key1 string
          Key2 string
        }
      }
    }
  }
}

var s setting
// after loading...
"value1" == s.Part1[0].Level1[0].Level2[0].Level3.Key1
```

**Comment by PlkMarudny** [comment]
Well, it panics. Using exactly the same config like above and the struct provided.

**Comment by delphinus** [comment]
The test code.  This can load config successfully.

```go
package main

import (
	"encoding/json"
	"os"

	"github.com/jinzhu/configor"
)

type setting struct {
	Part1 []struct {
		Level1 []struct {
			Level2 []struct {
				Level3 struct {
					Key1 string
					Key2 string
				}
			}
		}
	}
}

var s setting

func main() {
	c := configor.New(nil)
	if err := c.Load(&s, "config.yaml"); err != nil {
		panic(err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	if err := enc.Encode(s); err != nil {
		panic(err)
	}
}
```

```yaml
part1:
- level1:
  - level2:
    - level3:
        key1: value1
        key2: value2
```

and run

```json
go run configor.go
{
  "Part1": [
    {
      "Level1": [
        {
          "Level2": [
            {
              "Level3": {
                "Key1": "value1",
                "Key2": "value2"
              }
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by PlkMarudny** [comment]
Hi, Thanks for the answer, indeed the code above works. I am afraid I formulated the scenario in a wrong way. In my case, only the top level is fixed, i.e. **part1**, while **level1** has no fixed name (list of entries), but another level, **level2** has - ("templates" for each entry) and there are further variations like having the "buttons" list (or not) etc.

    showsandtemplates:  # <- this is fixed
    - tafaolkom:
        - templates:  # <- this is fixed
          - fetch:
             name: "Display name"
             mappings: # <- this is fixed
                  ScreenName: "001"
                  Message: "002"
                  ProfilePic: "003"
          - videowall:
              name: "Videowall full"
              mappings: 
                  ScreenName: "001"
                  Message: "002"
                  ProfilePic: "003"
                  Service: "004:
        - buttons:
             - Button1:
                   Type: "Ticker"
                   Label: "Ticker"
                   Color: "bg-blue"
    - 2 Hours:
        - templates:
            - socuniv:
                name: Social universal
                mappings:
                   ScreenName: "001"
                   Message: "003"
                   ProfilePic: "004"
                    Service: "005"

**Comment by delphinus** [comment]
I see... and it is probably impossible to load such yamls.  The keys of dict should be static to ride the way of Go.

The only thing you can do is to write custom Unmarshalling logic for the yaml.  But I do not recommend it.

**Comment by PlkMarudny** [comment]
Actually, this is what I did, I mean, I  unmarshall such a config in code, knowing the structure; tedious a little bit, but works.
