### ISSUE TITLE
使用yaml.v2的库不能build

### ISSUE THREAD

**Issue by dz1iang** [jinzhu/configor#38]
报错：
# github.com/jinzhu/configor
../../../jinzhu/configor/utils.go:102:11: undefined: yaml.UnmarshalStrict
../../../jinzhu/configor/utils.go:123:16: undefined: yaml.UnmarshalStrict

使用以下库代替解决：
"github.com/go-yaml/yaml"

**Comment by jinzhu** [comment]
应该没有用最新的版本吧
