### ISSUE TITLE
Obscure `invalid config, should be struct` error being thrown sometimes

### ISSUE THREAD

**Issue by Southclaws** [jinzhu/configor#40]
I had some users report the following issue: `failed to load configuration from '/myproject/pawn.json': invalid config, should be struct`.

This comes from the following line of code: https://github.com/Southclaws/sampctl/blob/master/types/package.go#L140

As you can see, `pkg` *is* a struct, it's a `types.Package` struct and is initialised by the return value definition. I can't reproduce this myself on my macbook though which is odd, my users are all on Windows afaik.

**Comment by DorianPeregrim** [comment]
Same error if I pass `map[string]string` instead struct in first argument `Load()`. But if I skip this error, content loads well.

**Comment by jinzhu** [comment]
Yes, only support struct.
