### ISSUE TITLE
Does not populate maps from environment variables

### ISSUE THREAD

**Issue by michaelkruglos** [jinzhu/configor#43]
Given the following struct:
```go
type Configuration struct {
  Item map[string]string
}
```
And environment variables:
```bash
CONFIGOR_CONFIGURATION_ITEM_KEY1=value1
CONFIGOR_CONFIGURATION_ITEM_KEY2=value2
```
The struct's `Item` is not populated.

**Comment by kimprado** [comment]
Decoder uses yaml to parse values.
One line define and use env:

`$ CONFIGOR_ITEM=$(echo -e "KEY1: value1\nKEY2: value2") go run main.go`

Or export and use:

`$ export CONFIGOR_ITEM=$(echo -e "KEY1: value1\nKEY2: value2")`
`$ echo $CONFIGOR_ITEM`
`KEY1: value1 KEY2: value2`
`go run main.go`

**Comment by michaelkruglos** [comment]
Thanks.
