### ISSUE TITLE
Loading configuration by env stops at struct bool if env is not a bool

### ISSUE THREAD

**Issue by alk-automize** [jinzhu/configor#47]
If env name is not a bool (true or false), e.g. 1 or 0, as described in struct, then it stops loading more env.

export ENVIRONMENT_ID=id
export ENVIRONMENT_NAME=name
export ENVIRONMENT_REUSE=1
export ENVIRONMENT_GROUP=group

Environment struct {
		ID       string `env:"ENVIRONMENT_ID"`
		Name     string `env:"ENVIRONMENT_NAME"`
		Reuse    bool   `env:"ENVIRONMENT_REUSE"`
		Group    string `env:"ENVIRONMENT_GROUP"`
}

Debug mode:
Loading configuration for struct 's field `ID` from env ENVIRONMENT_ID...
Loading configuration for struct 's field `Name` from env ENVIRONMENT_NAME...
Loading configuration for struct 's field `Reuse` from env ENVIRONMENT_REUSE...
Configuration:
...

**Comment by jinzhu** [comment]
Yes, the value should be able to decode to the field with json, otherwise, configor will return an error.

**Comment by alk-automize** [comment]
Maybe the debug output was not clear enough. There was no error message when configor tried to read ENVIRONMENT_REUSE, it failed silently and skipped reading ENVIRONMENT_GROUP.  Expected result would be that configor should complain that ENVIRONMENT_REUSE is not an bool and continue to read env values according to struct.

**Comment by jinzhu** [comment]
It should report detailed error, anyway, I have fixed this issue.
