### ISSUE TITLE
Can't parse list/array in YAML

### ISSUE THREAD

**Issue by chshawkn-pub** [jinzhu/configor#5]
My env is "go version go1.5.3 darwin/amd64"
Failed to parse Contacts in example code (result is Contacts:[]struct { Name string; Email string "required:\"true\"" }(nil)), only primitive type from shell environment is ok.

**Comment by zhl-home1** [comment]
Actually yaml config not work at all, but json is fine.
May be yaml2 lib's problem.

**Comment by jinzhu** [comment]
Is there any error returned when parse the configuration?

**Comment by hasghari** [comment]
I too was not able to get the yaml configuration to work. JSON is fine though.

**Comment by WanliTian** [comment]
when using this package, i got this: invalid config, should be struct

the wrong code is here: https://github.com/jinzhu/configor/blob/master/configor.go#L149

there are a sring slice, but processTags needs struct

**Comment by jinzhu** [comment]
Added an example in tests https://github.com/jinzhu/configor/commit/6c409036e1aea1420f2e1a196f95c0e3c4aef091
