### ISSUE TITLE
Ambiguous error message on required

### ISSUE THREAD

**Issue by prochac** [jinzhu/configor#51]
Hi, thanks for this project.
We have only one painfull issue with this library.
We use this for web services configuration and the config struct is nested and contains a lot of URLs to other services.

Sometimes we forgot to add secret to Vault, but error message is not much helpfull.

Here is our common usage
https://play.golang.org/p/XdV_kGtkQn7
```
package main

import (
	"fmt"
	"log"

	"github.com/jinzhu/configor"
)

type Config struct {
	InputService struct {
		URL string `env:"IN_SERVICE_URL" required:"true"`
	}
	OutputService struct {
		URL string `env:"OUT_SERVICE_URL" required:"true"`
	}
}

func main() {
	var config Config
	if err := configor.Load(&config); err != nil {
		log.Fatal(err) // URL is required, but blank
	}

	fmt.Println("Your config:", config)
}
```

**Comment by lukasaron** [comment]
The error is correct I would recommend to change the name of the field from `URL` into something more specific. The error will be more helpful then.

**Comment by prochac** [comment]
Ok, but it's anoying to have to use 
```
config.InputService.InputServiceURL
```
instead of 
```
config.InputService.URL
```
I planed to do a pull request for this issue but than I realized that even full name is not what I want.
```
InputService.URL is required, but blank
```
What I expect is more like
```
IN_SERVICE_URL variable is required, but blank
```
So I'm not using this lib anymore :) Not because it's bad.
But because anything simpler, for environment variables only, is enough for me.

**Comment by lukasaron** [comment]
You have assumptions based on the `env` variable in the tag. Such variable can be also empty when this value is filled from different source than ENV variable. To persist the logic on common bases you cannot rely on values that in tags. 

Existing logic returns the name of the field that is required and also empty.

Based on your provided code I would think about naming the field: `InputURL` or `InURL` and same format for output to distinguish between them.

**Comment by prochac** [comment]
Yeah, no doubt.

As I sayed, I don't use this lib anymore.

**Less is more** and it works for me.
I need to have the env vars only, following https://12factor.net/config, so I made a switch.
https://play.golang.org/p/ABZ7CuywNKQ
or good ol' [os.Getenv](https://golang.org/pkg/os/#Getenv) and [os.LookupEnv](https://golang.org/pkg/os/#LookupEnv).

And instead of .env, yaml, toml, ... files you can use shell file for shell sourcing the dev environment.
And without adding the extra complexity to app.
`$ . ./dev-env.sh` 
simple as pie

**Comment by prochac** [comment]
Not interested anymore.
