### ISSUE TITLE
Invalid config, should be struct

### ISSUE THREAD

**Issue by WanliTian** [jinzhu/configor#6]
I defined a struct to store my config  with two string slices. when using configor package, i got this:invalid config, should be struct

i dive into configor, i found this error is caused within: https://github.com/jinzhu/configor/blob/master/configor.go#L149

**Comment by csyangchen** [comment]
I think slice, except for struct is not supported.

	type Config struct {
		Hosts []string `yaml:"hosts""`
	}

I think for this case, don't return error at least.

**Comment by WanliTian** [comment]
@csyangchen  you are right. but it's a common case using a slice to store struct object.

**Comment by jinzhu** [comment]
Added an example in tests https://github.com/jinzhu/configor/commit/6c409036e1aea1420f2e1a196f95c0e3c4aef091
